services:
  sgivu-config:
    container_name: sgivu-config
    image: stevenrq/sgivu-config:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - sgivu-network
    environment:
      - SPRING_PROFILES_ACTIVE=git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/stevenrq/sgivu-config-repo.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main

  sgivu-discovery:
    container_name: sgivu-discovery
    image: stevenrq/sgivu-discovery:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sgivu-network
    env_file: .env

  sgivu-zipkin:
    container_name: sgivu-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - sgivu-network
    env_file: .env

  sgivu-auth:
    container_name: sgivu-auth
    image: stevenrq/sgivu-auth:v1
    ports:
      - "9000:9000"
    restart: always
    networks:
      - sgivu-network
    env_file: .env
    depends_on:
      - sgivu-config
      - sgivu-discovery

  sgivu-user:
    container_name: sgivu-user
    image: stevenrq/sgivu-user:v1
    ports:
      - "8081:8081"
    restart: always
    networks:
      - sgivu-network
    env_file: .env
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-client:
    container_name: sgivu-client
    image: stevenrq/sgivu-client:v1
    ports:
      - "8082:8082"
    restart: always
    networks:
      - sgivu-network
    env_file: .env
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-vehicle:
    container_name: sgivu-vehicle
    image: stevenrq/sgivu-vehicle:v1
    ports:
      - "8083:8083"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-gateway:
    container_name: sgivu-gateway
    image: stevenrq/sgivu-gateway:v1
    ports:
      - "8080:8080"
    restart: always
    networks:
      - sgivu-network
    env_file: .env
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

networks:
  sgivu-network:
    driver: bridge
