services:
  sgivu-mysql:
    container_name: sgivu-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    env_file: .env.dev
    networks:
      - sgivu-network
    volumes:
      - mysql-data:/var/lib/mysql

  sgivu-postgres:
    container_name: sgivu-postgres
    image: postgres:17.6
    ports:
      - "5432:5432"
    restart: always
    env_file: .env.dev
    networks:
      - sgivu-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  sgivu-config:
    container_name: sgivu-config
    image: stevenrq/sgivu-config:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev

  sgivu-discovery:
    container_name: sgivu-discovery
    image: stevenrq/sgivu-discovery:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev

  sgivu-zipkin:
    container_name: sgivu-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-mysql

  sgivu-auth:
    container_name: sgivu-auth
    image: stevenrq/sgivu-auth:v1
    ports:
      - "9000:9000"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-postgres

  sgivu-user:
    container_name: sgivu-user
    image: stevenrq/sgivu-user:v1
    ports:
      - "8081:8081"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth
      - sgivu-postgres

  sgivu-client:
    container_name: sgivu-client
    image: stevenrq/sgivu-client:v1
    ports:
      - "8082:8082"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth
      - sgivu-postgres

  sgivu-gateway:
    container_name: sgivu-gateway
    image: stevenrq/sgivu-gateway:v1
    ports:
      - "8080:8080"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

networks:
  sgivu-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
